"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-08 15:46:06.919643
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_id', sa.String(length=40), nullable=True),
    sa.Column('actor', sa.String(length=160), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=40), nullable=False),
    sa.Column('resource_id', sa.String(length=80), nullable=True),
    sa.Column('old_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('device_id', sa.String(length=64), nullable=True),
    sa.Column('request_id', sa.String(length=40), nullable=True),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_table('cases',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('attack_type', sa.String(length=60), nullable=False),
    sa.Column('severity', sa.String(length=12), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('recommended_action', sa.String(length=24), nullable=False),
    sa.Column('action_taken', sa.String(length=24), nullable=True),
    sa.Column('fusion', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('story', sa.Text(), nullable=False),
    sa.Column('primary_customer_id', sa.String(length=40), nullable=True),
    sa.Column('analyst_id', sa.String(length=40), nullable=True),
    sa.Column('raw_alert_count', sa.Integer(), nullable=False),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('amount_at_risk', sa.Float(), nullable=False),
    sa.Column('first_event_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_event_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('correlation_window_s', sa.Integer(), nullable=False),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_last_event_at'), 'cases', ['last_event_at'], unique=False)
    op.create_index(op.f('ix_cases_primary_customer_id'), 'cases', ['primary_customer_id'], unique=False)
    op.create_index(op.f('ix_cases_severity'), 'cases', ['severity'], unique=False)
    op.create_index(op.f('ix_cases_status'), 'cases', ['status'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('email_masked', sa.String(length=160), nullable=True),
    sa.Column('phone_masked', sa.String(length=40), nullable=True),
    sa.Column('email_enc', sa.LargeBinary(), nullable=True),
    sa.Column('phone_enc', sa.LargeBinary(), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('totp_secret_enc', sa.LargeBinary(), nullable=True),
    sa.Column('segment', sa.String(length=32), nullable=False),
    sa.Column('risk_tier', sa.String(length=16), nullable=False),
    sa.Column('home_city', sa.String(length=80), nullable=True),
    sa.Column('home_lat', sa.Float(), nullable=True),
    sa.Column('home_lon', sa.Float(), nullable=True),
    sa.Column('kyc_status', sa.String(length=24), nullable=False),
    sa.Column('population', sa.String(length=24), nullable=False),
    sa.Column('profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('event_type', sa.String(length=24), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source', sa.String(length=48), nullable=False),
    sa.Column('customer_id', sa.String(length=40), nullable=True),
    sa.Column('account_id', sa.String(length=40), nullable=True),
    sa.Column('device_id', sa.String(length=64), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('entities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=12), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('action', sa.String(length=24), nullable=True),
    sa.Column('reason_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('case_id', sa.String(length=40), nullable=True),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.Column('simulation_run_id', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_account_id'), 'events', ['account_id'], unique=False)
    op.create_index(op.f('ix_events_case_id'), 'events', ['case_id'], unique=False)
    op.create_index(op.f('ix_events_customer_id'), 'events', ['customer_id'], unique=False)
    op.create_index(op.f('ix_events_device_id'), 'events', ['device_id'], unique=False)
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_ip'), 'events', ['ip'], unique=False)
    op.create_index('ix_events_received', 'events', ['received_at'], unique=False)
    op.create_index(op.f('ix_events_simulation_run_id'), 'events', ['simulation_run_id'], unique=False)
    op.create_index(op.f('ix_events_ts'), 'events', ['ts'], unique=False)
    op.create_table('kyc_records',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('customer_id', sa.String(length=40), nullable=True),
    sa.Column('event_id', sa.String(length=40), nullable=True),
    sa.Column('doc_type', sa.String(length=40), nullable=False),
    sa.Column('doc_number_hmac', sa.String(length=64), nullable=True),
    sa.Column('fields_masked', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('checks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('decision', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kyc_records_customer_id'), 'kyc_records', ['customer_id'], unique=False)
    op.create_index(op.f('ix_kyc_records_doc_number_hmac'), 'kyc_records', ['doc_number_hmac'], unique=False)
    op.create_index(op.f('ix_kyc_records_event_id'), 'kyc_records', ['event_id'], unique=False)
    op.create_table('media_analyses',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('customer_id', sa.String(length=40), nullable=True),
    sa.Column('event_id', sa.String(length=40), nullable=True),
    sa.Column('media_type', sa.String(length=12), nullable=False),
    sa.Column('media_sha256', sa.String(length=64), nullable=False),
    sa.Column('fixture_name', sa.String(length=80), nullable=True),
    sa.Column('verdict', sa.String(length=32), nullable=False),
    sa.Column('deepfake_probability', sa.Float(), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_analyses_customer_id'), 'media_analyses', ['customer_id'], unique=False)
    op.create_index(op.f('ix_media_analyses_event_id'), 'media_analyses', ['event_id'], unique=False)
    op.create_table('model_registry',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('model_type', sa.String(length=80), nullable=False),
    sa.Column('framework', sa.String(length=40), nullable=False),
    sa.Column('domain', sa.String(length=24), nullable=False),
    sa.Column('training_date', sa.String(length=40), nullable=True),
    sa.Column('dataset', sa.Text(), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('artifact', sa.String(length=300), nullable=True),
    sa.Column('artifact_sha256', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_model_name_version', 'model_registry', ['name', 'version'], unique=True)
    op.create_table('otp_challenges',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('subject_id', sa.String(length=40), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('destination_masked', sa.String(length=64), nullable=True),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_challenges_subject_id'), 'otp_challenges', ['subject_id'], unique=False)
    op.create_table('policies',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('action', sa.String(length=24), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.String(length=160), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulation_runs',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('scenario', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_by', sa.String(length=160), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('total_steps', sa.Integer(), nullable=False),
    sa.Column('emitted', sa.Integer(), nullable=False),
    sa.Column('case_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('totp_secret_enc', sa.LargeBinary(), nullable=True),
    sa.Column('totp_pending_enc', sa.LargeBinary(), nullable=True),
    sa.Column('totp_last_step', sa.BigInteger(), nullable=True),
    sa.Column('failed_logins', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('verification_sessions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('customer_id', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('current_stage', sa.String(length=24), nullable=False),
    sa.Column('stages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('decision', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('device_id', sa.String(length=64), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_sessions_customer_id'), 'verification_sessions', ['customer_id'], unique=False)
    op.create_table('accounts',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('customer_id', sa.String(length=40), nullable=False),
    sa.Column('number_masked', sa.String(length=24), nullable=False),
    sa.Column('number_enc', sa.LargeBinary(), nullable=True),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_customer_id'), 'accounts', ['customer_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('event_id', sa.String(length=40), nullable=False),
    sa.Column('case_id', sa.String(length=40), nullable=True),
    sa.Column('detector', sa.String(length=40), nullable=False),
    sa.Column('domain', sa.String(length=24), nullable=False),
    sa.Column('severity', sa.String(length=12), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_case_id'), 'alerts', ['case_id'], unique=False)
    op.create_index(op.f('ix_alerts_event_id'), 'alerts', ['event_id'], unique=False)
    op.create_table('auth_sessions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('family_id', sa.String(length=40), nullable=False),
    sa.Column('refresh_hash', sa.String(length=64), nullable=False),
    sa.Column('device_id', sa.String(length=40), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.String(length=64), nullable=True),
    sa.Column('mfa_verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_hash')
    )
    op.create_index(op.f('ix_auth_sessions_family_id'), 'auth_sessions', ['family_id'], unique=False)
    op.create_index(op.f('ix_auth_sessions_user_id'), 'auth_sessions', ['user_id'], unique=False)
    op.create_table('case_actions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('case_id', sa.String(length=40), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('actor', sa.String(length=160), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_actions_case_id'), 'case_actions', ['case_id'], unique=False)
    op.create_table('case_entities',
    sa.Column('case_id', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('risk', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('case_id', 'entity_id')
    )
    op.create_table('case_events',
    sa.Column('case_id', sa.String(length=40), nullable=False),
    sa.Column('event_id', sa.String(length=40), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('case_id', 'event_id')
    )
    op.create_table('detections',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('event_id', sa.String(length=40), nullable=False),
    sa.Column('detector', sa.String(length=40), nullable=False),
    sa.Column('model_version', sa.String(length=80), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reason_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detections_detector'), 'detections', ['detector'], unique=False)
    op.create_index(op.f('ix_detections_event_id'), 'detections', ['event_id'], unique=False)
    op.create_table('face_templates',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('customer_id', sa.String(length=40), nullable=False),
    sa.Column('embedding_enc', sa.LargeBinary(), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_face_templates_customer_id'), 'face_templates', ['customer_id'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('case_id', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=24), nullable=False),
    sa.Column('actor_id', sa.String(length=40), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_case_id'), 'feedback', ['case_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('event_id', sa.String(length=40), nullable=False),
    sa.Column('customer_id', sa.String(length=40), nullable=True),
    sa.Column('account_id', sa.String(length=40), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('channel', sa.String(length=24), nullable=False),
    sa.Column('merchant_category', sa.String(length=40), nullable=True),
    sa.Column('beneficiary_id', sa.String(length=40), nullable=True),
    sa.Column('beneficiary_new', sa.Boolean(), nullable=False),
    sa.Column('fraud_probability', sa.Float(), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_account_id'), 'transactions', ['account_id'], unique=False)
    op.create_index(op.f('ix_transactions_beneficiary_id'), 'transactions', ['beneficiary_id'], unique=False)
    op.create_index(op.f('ix_transactions_customer_id'), 'transactions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_transactions_event_id'), 'transactions', ['event_id'], unique=False)
    op.create_index(op.f('ix_transactions_ts'), 'transactions', ['ts'], unique=False)
    op.create_table('user_devices',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('fingerprint_hash', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('trusted', sa.Boolean(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_ip', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_devices_user_fp', 'user_devices', ['user_id', 'fingerprint_hash'], unique=True)
    op.create_index(op.f('ix_user_devices_user_id'), 'user_devices', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_devices_user_id'), table_name='user_devices')
    op.drop_index('ix_user_devices_user_fp', table_name='user_devices')
    op.drop_table('user_devices')
    op.drop_index(op.f('ix_transactions_ts'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_event_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_customer_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_beneficiary_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_account_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_feedback_case_id'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_face_templates_customer_id'), table_name='face_templates')
    op.drop_table('face_templates')
    op.drop_index(op.f('ix_detections_event_id'), table_name='detections')
    op.drop_index(op.f('ix_detections_detector'), table_name='detections')
    op.drop_table('detections')
    op.drop_table('case_events')
    op.drop_table('case_entities')
    op.drop_index(op.f('ix_case_actions_case_id'), table_name='case_actions')
    op.drop_table('case_actions')
    op.drop_index(op.f('ix_auth_sessions_user_id'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_family_id'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_index(op.f('ix_alerts_event_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_case_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_accounts_customer_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_verification_sessions_customer_id'), table_name='verification_sessions')
    op.drop_table('verification_sessions')
    op.drop_table('users')
    op.drop_table('simulation_runs')
    op.drop_table('policies')
    op.drop_index(op.f('ix_otp_challenges_subject_id'), table_name='otp_challenges')
    op.drop_table('otp_challenges')
    op.drop_index('ix_model_name_version', table_name='model_registry')
    op.drop_table('model_registry')
    op.drop_index(op.f('ix_media_analyses_event_id'), table_name='media_analyses')
    op.drop_index(op.f('ix_media_analyses_customer_id'), table_name='media_analyses')
    op.drop_table('media_analyses')
    op.drop_index(op.f('ix_kyc_records_event_id'), table_name='kyc_records')
    op.drop_index(op.f('ix_kyc_records_doc_number_hmac'), table_name='kyc_records')
    op.drop_index(op.f('ix_kyc_records_customer_id'), table_name='kyc_records')
    op.drop_table('kyc_records')
    op.drop_index(op.f('ix_events_ts'), table_name='events')
    op.drop_index(op.f('ix_events_simulation_run_id'), table_name='events')
    op.drop_index('ix_events_received', table_name='events')
    op.drop_index(op.f('ix_events_ip'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_index(op.f('ix_events_device_id'), table_name='events')
    op.drop_index(op.f('ix_events_customer_id'), table_name='events')
    op.drop_index(op.f('ix_events_case_id'), table_name='events')
    op.drop_index(op.f('ix_events_account_id'), table_name='events')
    op.drop_table('events')
    op.drop_table('customers')
    op.drop_index(op.f('ix_cases_status'), table_name='cases')
    op.drop_index(op.f('ix_cases_severity'), table_name='cases')
    op.drop_index(op.f('ix_cases_primary_customer_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_last_event_at'), table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
